// Generated by gencpp from file clever/GetTelemetryRequest.msg
// DO NOT EDIT!


#ifndef CLEVER_MESSAGE_GETTELEMETRYREQUEST_H
#define CLEVER_MESSAGE_GETTELEMETRYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clever
{
template <class ContainerAllocator>
struct GetTelemetryRequest_
{
  typedef GetTelemetryRequest_<ContainerAllocator> Type;

  GetTelemetryRequest_()
    : frame_id()  {
    }
  GetTelemetryRequest_(const ContainerAllocator& _alloc)
    : frame_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _frame_id_type;
  _frame_id_type frame_id;





  typedef boost::shared_ptr< ::clever::GetTelemetryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clever::GetTelemetryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetTelemetryRequest_

typedef ::clever::GetTelemetryRequest_<std::allocator<void> > GetTelemetryRequest;

typedef boost::shared_ptr< ::clever::GetTelemetryRequest > GetTelemetryRequestPtr;
typedef boost::shared_ptr< ::clever::GetTelemetryRequest const> GetTelemetryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clever::GetTelemetryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clever::GetTelemetryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace clever

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::clever::GetTelemetryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clever::GetTelemetryRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clever::GetTelemetryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clever::GetTelemetryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clever::GetTelemetryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clever::GetTelemetryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clever::GetTelemetryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "371cb926969bb965addb80f752c7ca31";
  }

  static const char* value(const ::clever::GetTelemetryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x371cb926969bb965ULL;
  static const uint64_t static_value2 = 0xaddb80f752c7ca31ULL;
};

template<class ContainerAllocator>
struct DataType< ::clever::GetTelemetryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clever/GetTelemetryRequest";
  }

  static const char* value(const ::clever::GetTelemetryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clever::GetTelemetryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string frame_id\n"
;
  }

  static const char* value(const ::clever::GetTelemetryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clever::GetTelemetryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTelemetryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clever::GetTelemetryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clever::GetTelemetryRequest_<ContainerAllocator>& v)
  {
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.frame_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLEVER_MESSAGE_GETTELEMETRYREQUEST_H
