// Generated by gencpp from file clever/Navigate.msg
// DO NOT EDIT!


#ifndef CLEVER_MESSAGE_NAVIGATE_H
#define CLEVER_MESSAGE_NAVIGATE_H

#include <ros/service_traits.h>


#include <clever/NavigateRequest.h>
#include <clever/NavigateResponse.h>


namespace clever
{

struct Navigate
{

typedef NavigateRequest Request;
typedef NavigateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Navigate
} // namespace clever


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clever::Navigate > {
  static const char* value()
  {
    return "d27cf8a87020c28b3d14e06881a86c21";
  }

  static const char* value(const ::clever::Navigate&) { return value(); }
};

template<>
struct DataType< ::clever::Navigate > {
  static const char* value()
  {
    return "clever/Navigate";
  }

  static const char* value(const ::clever::Navigate&) { return value(); }
};


// service_traits::MD5Sum< ::clever::NavigateRequest> should match 
// service_traits::MD5Sum< ::clever::Navigate > 
template<>
struct MD5Sum< ::clever::NavigateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::clever::Navigate >::value();
  }
  static const char* value(const ::clever::NavigateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clever::NavigateRequest> should match 
// service_traits::DataType< ::clever::Navigate > 
template<>
struct DataType< ::clever::NavigateRequest>
{
  static const char* value()
  {
    return DataType< ::clever::Navigate >::value();
  }
  static const char* value(const ::clever::NavigateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clever::NavigateResponse> should match 
// service_traits::MD5Sum< ::clever::Navigate > 
template<>
struct MD5Sum< ::clever::NavigateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clever::Navigate >::value();
  }
  static const char* value(const ::clever::NavigateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clever::NavigateResponse> should match 
// service_traits::DataType< ::clever::Navigate > 
template<>
struct DataType< ::clever::NavigateResponse>
{
  static const char* value()
  {
    return DataType< ::clever::Navigate >::value();
  }
  static const char* value(const ::clever::NavigateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLEVER_MESSAGE_NAVIGATE_H
