// Generated by gencpp from file clever/NavigateGlobalRequest.msg
// DO NOT EDIT!


#ifndef CLEVER_MESSAGE_NAVIGATEGLOBALREQUEST_H
#define CLEVER_MESSAGE_NAVIGATEGLOBALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clever
{
template <class ContainerAllocator>
struct NavigateGlobalRequest_
{
  typedef NavigateGlobalRequest_<ContainerAllocator> Type;

  NavigateGlobalRequest_()
    : lat(0.0)
    , lon(0.0)
    , z(0.0)
    , yaw(0.0)
    , yaw_rate(0.0)
    , speed(0.0)
    , frame_id()
    , auto_arm(false)  {
    }
  NavigateGlobalRequest_(const ContainerAllocator& _alloc)
    : lat(0.0)
    , lon(0.0)
    , z(0.0)
    , yaw(0.0)
    , yaw_rate(0.0)
    , speed(0.0)
    , frame_id(_alloc)
    , auto_arm(false)  {
  (void)_alloc;
    }



   typedef double _lat_type;
  _lat_type lat;

   typedef double _lon_type;
  _lon_type lon;

   typedef float _z_type;
  _z_type z;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _yaw_rate_type;
  _yaw_rate_type yaw_rate;

   typedef float _speed_type;
  _speed_type speed;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _frame_id_type;
  _frame_id_type frame_id;

   typedef uint8_t _auto_arm_type;
  _auto_arm_type auto_arm;





  typedef boost::shared_ptr< ::clever::NavigateGlobalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clever::NavigateGlobalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NavigateGlobalRequest_

typedef ::clever::NavigateGlobalRequest_<std::allocator<void> > NavigateGlobalRequest;

typedef boost::shared_ptr< ::clever::NavigateGlobalRequest > NavigateGlobalRequestPtr;
typedef boost::shared_ptr< ::clever::NavigateGlobalRequest const> NavigateGlobalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clever::NavigateGlobalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clever::NavigateGlobalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace clever

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::clever::NavigateGlobalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clever::NavigateGlobalRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clever::NavigateGlobalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clever::NavigateGlobalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clever::NavigateGlobalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clever::NavigateGlobalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clever::NavigateGlobalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "00459843364a05483481c18c2838cd0d";
  }

  static const char* value(const ::clever::NavigateGlobalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x00459843364a0548ULL;
  static const uint64_t static_value2 = 0x3481c18c2838cd0dULL;
};

template<class ContainerAllocator>
struct DataType< ::clever::NavigateGlobalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clever/NavigateGlobalRequest";
  }

  static const char* value(const ::clever::NavigateGlobalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clever::NavigateGlobalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 lat\n"
"float64 lon\n"
"float32 z\n"
"float32 yaw\n"
"float32 yaw_rate\n"
"float32 speed\n"
"string frame_id\n"
"bool auto_arm\n"
;
  }

  static const char* value(const ::clever::NavigateGlobalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clever::NavigateGlobalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lat);
      stream.next(m.lon);
      stream.next(m.z);
      stream.next(m.yaw);
      stream.next(m.yaw_rate);
      stream.next(m.speed);
      stream.next(m.frame_id);
      stream.next(m.auto_arm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigateGlobalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clever::NavigateGlobalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clever::NavigateGlobalRequest_<ContainerAllocator>& v)
  {
    s << indent << "lat: ";
    Printer<double>::stream(s, indent + "  ", v.lat);
    s << indent << "lon: ";
    Printer<double>::stream(s, indent + "  ", v.lon);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "yaw_rate: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_rate);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.frame_id);
    s << indent << "auto_arm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.auto_arm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLEVER_MESSAGE_NAVIGATEGLOBALREQUEST_H
