// Generated by gencpp from file clever/SetAttitudeRequest.msg
// DO NOT EDIT!


#ifndef CLEVER_MESSAGE_SETATTITUDEREQUEST_H
#define CLEVER_MESSAGE_SETATTITUDEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clever
{
template <class ContainerAllocator>
struct SetAttitudeRequest_
{
  typedef SetAttitudeRequest_<ContainerAllocator> Type;

  SetAttitudeRequest_()
    : pitch(0.0)
    , roll(0.0)
    , yaw(0.0)
    , thrust(0.0)
    , frame_id()
    , auto_arm(false)  {
    }
  SetAttitudeRequest_(const ContainerAllocator& _alloc)
    : pitch(0.0)
    , roll(0.0)
    , yaw(0.0)
    , thrust(0.0)
    , frame_id(_alloc)
    , auto_arm(false)  {
  (void)_alloc;
    }



   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _thrust_type;
  _thrust_type thrust;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _frame_id_type;
  _frame_id_type frame_id;

   typedef uint8_t _auto_arm_type;
  _auto_arm_type auto_arm;





  typedef boost::shared_ptr< ::clever::SetAttitudeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clever::SetAttitudeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetAttitudeRequest_

typedef ::clever::SetAttitudeRequest_<std::allocator<void> > SetAttitudeRequest;

typedef boost::shared_ptr< ::clever::SetAttitudeRequest > SetAttitudeRequestPtr;
typedef boost::shared_ptr< ::clever::SetAttitudeRequest const> SetAttitudeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clever::SetAttitudeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clever::SetAttitudeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace clever

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::clever::SetAttitudeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clever::SetAttitudeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clever::SetAttitudeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clever::SetAttitudeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clever::SetAttitudeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clever::SetAttitudeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clever::SetAttitudeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57b7e3577c60ddfb174e6a5be8792292";
  }

  static const char* value(const ::clever::SetAttitudeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57b7e3577c60ddfbULL;
  static const uint64_t static_value2 = 0x174e6a5be8792292ULL;
};

template<class ContainerAllocator>
struct DataType< ::clever::SetAttitudeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clever/SetAttitudeRequest";
  }

  static const char* value(const ::clever::SetAttitudeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clever::SetAttitudeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pitch\n"
"float32 roll\n"
"float32 yaw\n"
"float32 thrust\n"
"string frame_id\n"
"bool auto_arm\n"
;
  }

  static const char* value(const ::clever::SetAttitudeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clever::SetAttitudeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pitch);
      stream.next(m.roll);
      stream.next(m.yaw);
      stream.next(m.thrust);
      stream.next(m.frame_id);
      stream.next(m.auto_arm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetAttitudeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clever::SetAttitudeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clever::SetAttitudeRequest_<ContainerAllocator>& v)
  {
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "thrust: ";
    Printer<float>::stream(s, indent + "  ", v.thrust);
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.frame_id);
    s << indent << "auto_arm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.auto_arm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLEVER_MESSAGE_SETATTITUDEREQUEST_H
