// Generated by gencpp from file clever/SetLEDEffectRequest.msg
// DO NOT EDIT!


#ifndef CLEVER_MESSAGE_SETLEDEFFECTREQUEST_H
#define CLEVER_MESSAGE_SETLEDEFFECTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clever
{
template <class ContainerAllocator>
struct SetLEDEffectRequest_
{
  typedef SetLEDEffectRequest_<ContainerAllocator> Type;

  SetLEDEffectRequest_()
    : effect()
    , r(0)
    , g(0)
    , b(0)  {
    }
  SetLEDEffectRequest_(const ContainerAllocator& _alloc)
    : effect(_alloc)
    , r(0)
    , g(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _effect_type;
  _effect_type effect;

   typedef uint8_t _r_type;
  _r_type r;

   typedef uint8_t _g_type;
  _g_type g;

   typedef uint8_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::clever::SetLEDEffectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clever::SetLEDEffectRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetLEDEffectRequest_

typedef ::clever::SetLEDEffectRequest_<std::allocator<void> > SetLEDEffectRequest;

typedef boost::shared_ptr< ::clever::SetLEDEffectRequest > SetLEDEffectRequestPtr;
typedef boost::shared_ptr< ::clever::SetLEDEffectRequest const> SetLEDEffectRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clever::SetLEDEffectRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clever::SetLEDEffectRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace clever

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::clever::SetLEDEffectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clever::SetLEDEffectRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clever::SetLEDEffectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clever::SetLEDEffectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clever::SetLEDEffectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clever::SetLEDEffectRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clever::SetLEDEffectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f671ae8175b9ebc5acde7321ebe360c1";
  }

  static const char* value(const ::clever::SetLEDEffectRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf671ae8175b9ebc5ULL;
  static const uint64_t static_value2 = 0xacde7321ebe360c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::clever::SetLEDEffectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clever/SetLEDEffectRequest";
  }

  static const char* value(const ::clever::SetLEDEffectRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clever::SetLEDEffectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string effect\n"
"uint8 r\n"
"uint8 g\n"
"uint8 b\n"
;
  }

  static const char* value(const ::clever::SetLEDEffectRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clever::SetLEDEffectRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.effect);
      stream.next(m.r);
      stream.next(m.g);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetLEDEffectRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clever::SetLEDEffectRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clever::SetLEDEffectRequest_<ContainerAllocator>& v)
  {
    s << indent << "effect: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.effect);
    s << indent << "r: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.r);
    s << indent << "g: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.g);
    s << indent << "b: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLEVER_MESSAGE_SETLEDEFFECTREQUEST_H
