// Generated by gencpp from file clever/SetRatesRequest.msg
// DO NOT EDIT!


#ifndef CLEVER_MESSAGE_SETRATESREQUEST_H
#define CLEVER_MESSAGE_SETRATESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clever
{
template <class ContainerAllocator>
struct SetRatesRequest_
{
  typedef SetRatesRequest_<ContainerAllocator> Type;

  SetRatesRequest_()
    : pitch_rate(0.0)
    , roll_rate(0.0)
    , yaw_rate(0.0)
    , thrust(0.0)
    , auto_arm(false)  {
    }
  SetRatesRequest_(const ContainerAllocator& _alloc)
    : pitch_rate(0.0)
    , roll_rate(0.0)
    , yaw_rate(0.0)
    , thrust(0.0)
    , auto_arm(false)  {
  (void)_alloc;
    }



   typedef float _pitch_rate_type;
  _pitch_rate_type pitch_rate;

   typedef float _roll_rate_type;
  _roll_rate_type roll_rate;

   typedef float _yaw_rate_type;
  _yaw_rate_type yaw_rate;

   typedef float _thrust_type;
  _thrust_type thrust;

   typedef uint8_t _auto_arm_type;
  _auto_arm_type auto_arm;





  typedef boost::shared_ptr< ::clever::SetRatesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clever::SetRatesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetRatesRequest_

typedef ::clever::SetRatesRequest_<std::allocator<void> > SetRatesRequest;

typedef boost::shared_ptr< ::clever::SetRatesRequest > SetRatesRequestPtr;
typedef boost::shared_ptr< ::clever::SetRatesRequest const> SetRatesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clever::SetRatesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clever::SetRatesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace clever

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::clever::SetRatesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clever::SetRatesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clever::SetRatesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clever::SetRatesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clever::SetRatesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clever::SetRatesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clever::SetRatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af3af5eb1fdd1e1bcaa59b13f3881fdb";
  }

  static const char* value(const ::clever::SetRatesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf3af5eb1fdd1e1bULL;
  static const uint64_t static_value2 = 0xcaa59b13f3881fdbULL;
};

template<class ContainerAllocator>
struct DataType< ::clever::SetRatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clever/SetRatesRequest";
  }

  static const char* value(const ::clever::SetRatesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clever::SetRatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pitch_rate\n"
"float32 roll_rate\n"
"float32 yaw_rate\n"
"float32 thrust\n"
"bool auto_arm\n"
;
  }

  static const char* value(const ::clever::SetRatesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clever::SetRatesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pitch_rate);
      stream.next(m.roll_rate);
      stream.next(m.yaw_rate);
      stream.next(m.thrust);
      stream.next(m.auto_arm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRatesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clever::SetRatesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clever::SetRatesRequest_<ContainerAllocator>& v)
  {
    s << indent << "pitch_rate: ";
    Printer<float>::stream(s, indent + "  ", v.pitch_rate);
    s << indent << "roll_rate: ";
    Printer<float>::stream(s, indent + "  ", v.roll_rate);
    s << indent << "yaw_rate: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_rate);
    s << indent << "thrust: ";
    Printer<float>::stream(s, indent + "  ", v.thrust);
    s << indent << "auto_arm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.auto_arm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLEVER_MESSAGE_SETRATESREQUEST_H
