// Generated by gencpp from file clever/SetRates.msg
// DO NOT EDIT!


#ifndef CLEVER_MESSAGE_SETRATES_H
#define CLEVER_MESSAGE_SETRATES_H

#include <ros/service_traits.h>


#include <clever/SetRatesRequest.h>
#include <clever/SetRatesResponse.h>


namespace clever
{

struct SetRates
{

typedef SetRatesRequest Request;
typedef SetRatesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRates
} // namespace clever


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clever::SetRates > {
  static const char* value()
  {
    return "a9cc2408dc007c6dd1f503c73d267539";
  }

  static const char* value(const ::clever::SetRates&) { return value(); }
};

template<>
struct DataType< ::clever::SetRates > {
  static const char* value()
  {
    return "clever/SetRates";
  }

  static const char* value(const ::clever::SetRates&) { return value(); }
};


// service_traits::MD5Sum< ::clever::SetRatesRequest> should match 
// service_traits::MD5Sum< ::clever::SetRates > 
template<>
struct MD5Sum< ::clever::SetRatesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::clever::SetRates >::value();
  }
  static const char* value(const ::clever::SetRatesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clever::SetRatesRequest> should match 
// service_traits::DataType< ::clever::SetRates > 
template<>
struct DataType< ::clever::SetRatesRequest>
{
  static const char* value()
  {
    return DataType< ::clever::SetRates >::value();
  }
  static const char* value(const ::clever::SetRatesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clever::SetRatesResponse> should match 
// service_traits::MD5Sum< ::clever::SetRates > 
template<>
struct MD5Sum< ::clever::SetRatesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clever::SetRates >::value();
  }
  static const char* value(const ::clever::SetRatesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clever::SetRatesResponse> should match 
// service_traits::DataType< ::clever::SetRates > 
template<>
struct DataType< ::clever::SetRatesResponse>
{
  static const char* value()
  {
    return DataType< ::clever::SetRates >::value();
  }
  static const char* value(const ::clever::SetRatesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLEVER_MESSAGE_SETRATES_H
